[package]
name = "iroh-sync"
version = "0.4.1"
edition = "2021"
readme = "README.md"
description = "IPFS sync"
license = "MIT/Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh-sync"

[dependencies]
